alphavantage:
  url: https://www.alphavantage.co
server:
  port: 50099

spring:
  session:
    store-type: redis
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    com.binance: OFF
    ee.tenman.stocks.alphavantage: OFF
